# Generated by Django 6.0.7 on 2026-08-06 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='categoty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='costs.category'),
            preserve_default=False,
        ),
    ]
