# Generated by Django 6.0.7 on 2026-08-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_expense_categoty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categoty',
            new_name='category',
        ),
    ]
