# Generated by Django 6.0.7 on 2026-08-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_rename_categoty_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=200)),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
