# Generated by Django 6.0.7 on 2026-08-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_wallet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
